// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/11/2026, 7:10:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/iyan/NodeStudio/hr-app-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/plugins/**/*.{js,ts,mjs}","/Users/iyan/NodeStudio/hr-app-frontend/composables/**/*.{js,ts,mjs}","/Users/iyan/NodeStudio/hr-app-frontend/utils/**/*.{js,ts,mjs}","/Users/iyan/NodeStudio/hr-app-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/iyan/NodeStudio/hr-app-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;